McNamara84/elmo

formgroups/resourceInformation.html, lang/de.php, lang/en.php, lang/fr.php
Warnhinweis bei deaktiviertem JavaScript implementiert:
- Verwendung des noscript-Elements aus HTML5 zur Anzeige eines Warnhinweises, wenn Nutzende JavaScript im Browser aktiv unterdrücken oder in den Einstellungen deaktiviert haben.
- Übersetzung des Warnhinweises in alle drei aktuell verfügbaren Sprachdateien
- Fixed #110
=> Fehlermeldung bei deaktiviertem JavaScript

.htaccess, README.md, api/v2/docs/swagger.yaml, api/v2/index.php, doc/help.html, formgroups/authors.html, formgroups/contributors.html, formgroups/resourceInformation.html, formgroups/spatialtemporalcoverage.html, js/buttons.js, lang/de.php, lang/en.php, lang/fr.php
In diesem Branch wurde folgendes gefixed:
- Der Pattern in dem Eingabefeld "Title" wurde bearbeitet. #119 
- fehlende "div" in der Help Guide wurde vervollständigt.
- invalid-Nachricht für ORCID Felder vereinheitlicht. #126
- Die Hilfe-Buttons wurden in den "FG"  Originating Laboratory und Funding Reference in den geklonten Zeile entfernt. #118 
- Hilfebutton für das Feld Publication Year eingefügt. #131 
- Uhrzeiten in TSC auf optionale Felder umgestellt. #122 
- Pfadangaben relativ angegeben, Code dokumentiert nach PHPDoc-Standard #138
=> Bugfixes Sprint 3

tests/SeleniumTests/Tests_MDE.side
In diesem Branch wurde ein Selenium-Projekt hinzugefügt (im Ordner tests->SeleniumTests)
Zur Nutzung muss Selenium IDE im Browser installiert werden. Dann das Projekt öffnen und testen :) 
ACHTUNG: der Link im jeweils ersten Command muss auf den jeweiligen lokalen Pfad angepasst werden
Enthalten sind erste Tests:
- **AlleFelderausgefüllt** befüllt alle z.Zt. sichtbaren Felder mit validen Werten und speichert
- **Default-Einstellungen** testet, ob inputLanguageDataset Englisch ist und inputRights CC-BY-4.0
- **HilfebuttonsRessourceInformation** testet, ob alle Hilfe-Buttons in der fg Resource Information anklickbar sind und die Überschrift des Modals dem jeweiligen Feld entspricht
- **Lizenzen** testet, ob alle 6 Lizenzen auswählbar sind
- **PflichtfelderAusgefüllt** befüllt alle derzeit …
=> Selenium tests

formgroups/contactpersons.html, js/buttons.js
Dieser Fix behebt das Problem #232 :
Improvements to form clarity:
* Updated comments in `formgroups/contactpersons.html` to change German labels to English and make them more descriptive. [[1]](diffhunk://#diff-2fb61cef92139b9b56f6319934602ce96c0b3377064d0ada249bc1b28ce8b92dL8-R8) [[2]](diffhunk://#diff-2fb61cef92139b9b56f6319934602ce96c0b3377064d0ada249bc1b28ce8b92dL23-R23) [[3]](diffhunk://#diff-2fb61cef92139b9b56f6319934602ce96c0b3377064d0ada249bc1b28ce8b92dL39-R38) [[4]](diffhunk://#diff-2fb61cef92139b9b56f6319934602ce96c0b3377064d0ada249bc1b28ce8b92dL59-R57) [[5]](diffhunk://#diff-2fb61cef92139b9b56f6319934602ce96c0b3377064d0ada249bc1b28ce8b92dL76-R73) [[6]](diffhunk://#diff-2fb61cef92139b9b56f6319934602ce96c0b3377064d0ada249bc1b28ce8b92dL97-R93) …
=> Bugfix: Geklonte Zeilen für Contact Persons haben kein funktionierendes Affiliations-Feld

README.md, formgroups/originatingLaboratory.html
Dieser Pull Request entfernt das **Affiliations Feld der Originating Laboratories** für die Augen der Nutzer bzw. aus der GUI.
* Removed outdated information about laboratory affiliation from the `README.md` file.
* Updated the input field for the laboratory name to increase its width and changed the comment to English for better clarity.
* Changed the laboratory affiliation input field to be hidden and updated the comment to reflect this change.
* Updated the button comment to indicate it is for cloning a new row, improving clarity.
* Removed an unnecessary blank line for cleaner code formatting.
=> Feature: Hide lab affiliation from user

js/buttons.js, js/select.js
Fixed #238 
Dieser Pull Request löst das Problem, dass **geklonte Funder-Zeilen keine Autocomplete-Funktion** haben.
Improvements to autocomplete functionality:
* [`js/buttons.js`](diffhunk://#diff-11827509078cde32f784e7e2265e5653cee1355115948e6de3e53fbbf44f14adL595-R599): Added logic to destroy existing autocomplete before reinitializing it for a new input field to prevent conflicts.
Code cleanup:
* [`js/buttons.js`](diffhunk://#diff-11827509078cde32f784e7e2265e5653cee1355115948e6de3e53fbbf44f14adL571-L574): Removed unnecessary comments and cleaned up the cloning process for new funding reference rows.
* [`js/select.js`](diffhunk://#diff-f23639ab50ee01de087486418e0e652284a0a5e6d05cc0698a6e85521bb46a38L23-L25): Removed unused initialization of the Chosen plugin for role selection fields. …
=> Bugfix: Autocomplete für geklonte Zeilen in Funders Reference

doc/changelog.html, js/mappingXmlToInputFields.js
Dieser Pull Request ergänzt das **Laden der Descriptions aus der hochgeladenen XML-Datei**.
* [`js/mappingXmlToInputFields.js`](diffhunk://#diff-67c1fa1d0f6d5ed82d952e3b2cdacac9fa7f7565e11567a1224cae30c3ad4b85R715-R767): Added a new function `processDescriptions` to process description elements from an XML document and populate the form fields accordingly. This includes mapping description types to form input IDs, resetting all description fields, and setting the content in the appropriate text areas.
* [`js/mappingXmlToInputFields.js`](diffhunk://#diff-67c1fa1d0f6d5ed82d952e3b2cdacac9fa7f7565e11567a1224cae30c3ad4b85R927-R928): Updated the `loadXmlToForm` function to call the new `processDescriptions` function, ensuring that descriptions are processed when loading XML data into form …
=> Feature: Load to XML for Descriptions

js/validation.js, save/save_data.php
Dieser Pull Request fixt den Bug, durch den beim **Speichern der Datensatz doppelt** angelegt wurde und löst damit #386 .
Dieser Pull-Request enthält wichtige Aktualisierungen der Dateien `js/validation.js` und `save/save_data.php`, um die Formularvalidierung, die Bearbeitung der Übermittlung und die Dateispeicherung zu verbessern. Die Änderungen konzentrieren sich auf Code-Refactoring, Modularisierung und die Verbesserung der Funktionalität.
* **Refactoring and Modularization**:
- Consolidated modal initialization into a single object for better manageability. (`[js/validation.jsL13-R24](diffhunk://#diff-aa91429cf8f6d96d622593e0f7e520324ab1243467970715f3c5015111abebd9L13-R24)`)
- Introduced `initializeFormControls` function to set up form controls and event listeners. …
=> Fix: Saving created two data records in database

.github/workflows/selenium.yml
Dieser Hotfix erhöht die Versionsnummer der **GitHub Action upload-artifact auf v4** damit Selenium Tests wieder ausgeführt werden.
* [`.github/workflows/selenium.yml`](diffhunk://#diff-da608d47fecd5a4550380c7c363b127094b8550427958aa2a8419d4dd5416214L239-R239): Updated the `upload-artifact` action from version 3 to version 4.
_Keine._
Ob die Selenium-Test auch wirklich ausgeführt werden, ist weiterhin fraglich.
=> Hotfix: GitHub Action für Selenium-Tests aktualisiert

footer.html
Warum auch immer: Der Clearbutton war kaputt, jetzt geht er wieder.
ich habe das wort disabled aus dem Clear Button entfernt
--
Ich wüsste gerne, warum das passiert ist und wie sich sowas in Zukunft verhindern lässt.
=> enable clear button

api/v2/controllers/VocabController.php, api/v2/docs/swagger.yaml, api/v2/routes/api.php, tests/ApiTest.php
This pull request moves functionality to retrieve CGI Simple Lithology keywords and integrates it into the APIv2. The most important changes include adding a new method to handle the retrieval of these keywords, updating the API routes, and documenting the new endpoint in the Swagger specification.
Fixes #61 
* [`api/v2/controllers/VocabController.php`](diffhunk://#diff-b9667eda042481bdf5e70cbb02cd5b4e00a9ccc21b5ea5de5e8437c68bff2fa8R358-R381): Added the `getCGIKeywords()` method to retrieve CGI Simple Lithology keywords from a local JSON file, handle errors gracefully, and return the data as JSON.
* [`api/v2/routes/api.php`](diffhunk://#diff-df40779a952ef6bed2a68ca3827ca48b8bdf44ff2e94754b4f04162da7693282R28): Added a new route `/vocabs/cgi` to map the `getCGIKeywords()` method for …
=> API: Moved API endpoint for CGI Simple Lithology vocabulary to new APIv2

api/v2/controllers/DatasetController.php, save/save_data.php, send_xml_file.php
Es geht um save and submit Funktionalitäten. Die hier genutzte Methode ist diese: debug extistierende Lösung + eine neue Lösung implementieren für den Fall, dass das nicht gut functioniert. 
Die existierende Logik ist API Endpunkt zu benutzen. Das ist kompakt und nutzt null Memory, aber das kann scwierig für ein Container sein (wie zbs. bei mir lokal), zu sich selbst ein HTTP request zu senden.
Die neue Logik spielt eine Rolle nur dann, wann die existierende nicht funktioniert. Die Idee ist DatasetController zu nutzen, um envelope XMLs on-the-fly oder in-memory zu produzieren. 
Diese 2-Methode doppelgesicherte Strategie ist für save_data.php und send_xml_file.php implementiert
Neue public Method ist in DatasetController implementiert. Das "publiziert" HandleExportAll Method.
**Logging** …
=> Fix: save and submit buttons working propperly

README.md, doc/help.html, footer.html, header.php, package-lock.json, package.json, tests/js/affiliations.test.js, tests/js/autocomplete.test.js
This pull request introduces several changes aimed at improving dependency management, transitioning to local libraries, and enhancing unit testing. The most significant updates include replacing CDN-based dependencies with locally managed ones, adding new dependencies to `package.json`, and updating tests to use the imported `jQuery` library instead of custom stubs.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L211-R215): Updated third-party dependency descriptions to reflect the transition from specific version numbers to general library names (e.g., `jQuery 3.7.1` to `jQuery 3`).
* `header.php`, `footer.html`, and `doc/help.html`: Replaced CDN references for `jQuery`, `jQuery UI`, and `Tagify` with local paths pointing to …
=> Chore: Moved jQuery from CDN to npm installation and unit tests for automcomplete.js

api/v2/controllers/VocabController.php, api/v2/docs/swagger.yaml, api/v2/routes/api.php, formgroups/resourceInformation.html, index.php, js/mappingXmlToInputFields.js, js/select.js, tests/js/mappingXmlToInputFields.test.js, tests/js/select.test.js
This pull request introduces functionality to retrieve and manage language data via an API, integrating it into both the backend and frontend systems. The changes include adding a new API endpoint, updating the frontend to dynamically populate language dropdowns, and adding corresponding tests to ensure reliability.
These changes improve the system's flexibility and maintainability by centralizing language data management and enhancing the user experience with dynamic dropdowns.
Closes #358 
* **New API Endpoint for Languages**: Added a `getLanguages` method in `VocabController` to fetch language data from the database and return it as JSON.
* **API Documentation**: Updated `swagger.yaml` to document the new `/vocabs/languages` endpoint and defined a `Language` schema. …
=> Feature: New API endpoint for language of dataset options

sample_settings_gem.php, sample_settings_msl.php, send_feedback_mail.php, send_xml_file.php
This pull request focuses on improving code readability and consistency by translating German comments into English across several PHP files. The changes help make the codebase more accessible to non-German speakers and clarify the intent of various configuration and logic sections.
Comment translation and clarity improvements:
* Changed comments in `send_feedback_mail.php` to English, clarifying steps such as DNS and port tests, network testing, debug settings, server configuration, authentication, STARTTLS, email body, fallback handling, and POST request processing. [[1]](diffhunk://#diff-0d65470af8405c666ff560010d9eb8b7a55e8b32ab32ff097f41ae57b2c3a844L16-R20) [[2]](diffhunk://#diff-0d65470af8405c666ff560010d9eb8b7a55e8b32ab32ff097f41ae57b2c3a844L43-R43) …
=> Ensure comments are English

header.php
This pull request updates the logic for determining the base URL in the `header.php` file to better handle reverse proxy setups and script locations, and slightly modifies the HTML escaping for the base URL. The most important changes are:
* Changed `$baseHref` to use the directory name of `$_SERVER['SCRIPT_NAME']` instead of a hardcoded `'/'`, making the base URL more accurate for different script locations.
* Updated the logic to ensure that if the `HTTP_X_FORWARDED_PREFIX` header is present (common in reverse proxy setups), its value is used for the base URL, improving compatibility with proxied deployments.
* Removed explicit character encoding parameters from the `htmlspecialchars` call for the base URL in the `<base>` tag, relying on default behavior instead.
Should only be reviewed …
=> Fix: Ali cannot use XAMPP for local testing

tests/SaveDescriptionsTest.php, tests/SaveFreekeywordsTest.php, tests/SaveGGMsProperties.php, tests/SaveSpatialTemporalCoverageTest.php, tests/js/affiliations.test.js
This pull request refactors and improves the test suites for saving descriptions, free keywords, Gravity Gradient Model properties, and spatial/temporal coverage. The main focus is on enhancing code readability, consistency, and maintainability. Changes include updating test method signatures to specify `void` return types, converting comments and assertion messages from German to clear English, and providing more descriptive docblocks for each test case.
* All test method signatures in `tests/SaveDescriptionsTest.php`, `tests/SaveFreekeywordsTest.php`, `tests/SaveGGMsProperties.php`, and `tests/SaveSpatialTemporalCoverageTest.php` now explicitly declare `: void` return types, improving type safety and clarity. [[1]](diffhunk://#diff-c3f63078e98a4966428b03d61b54e48ffe450f661b2ed52b533a58a0 …
=> Doc: Enhanced and translate PHPDoc comments in tests

doc/changelog.html, save/formgroups/save_thesauruskeywords.php
This pull request introduces a targeted fix to how MSL keywords are handled and documented. The main change ensures that MSL keywords are consistently saved with the "EPOS MSL vocabulary" scheme, both in the backend logic and in the changelog documentation.
- Fixes #588 
* Updated the `processThesaurusKeyword` function in `save/formgroups/save_thesauruskeywords.php` to always save MSL keywords with the "EPOS MSL vocabulary" scheme as a workaround for a known upstream issue.
* Added a changelog entry in `doc/changelog.html` noting that MSL keywords are now saved with the "EPOS MSL vocabulary" scheme.
* Minor formatting adjustment in the changelog by removing an unnecessary blank line.
None.
None.
=> Fix: Set scheme name for MSL keyword to EPOS MSL vocabulary

README.md, docker-compose.prod.yml, sample_settings_gem.php, sample_settings_msl.php, settings.msl.php, stack.env
This pull request updates the way XML submission addresses are configured for the MSL and GEM services, making the environment variables more explicit and reducing the risk of misconfiguration. The changes ensure that each service uses its own dedicated environment variable for the XML submission address, both in the Docker Compose configuration and in the PHP settings files.
Fixes #683 
* Added new environment variables `XML_SUBMIT_ADDRESS_MSL` and `XML_SUBMIT_ADDRESS_GEM` to `stack.env` for clearer separation of XML submission addresses for MSL and GEM services.
* Updated `docker-compose.prod.yml` to use `XML_SUBMIT_ADDRESS_MSL` for the MSL service and `XML_SUBMIT_ADDRESS_GEM` for the GEM service, replacing the previous shared `XML_SUBMIT_ADDRESS`. …
=> Fix: All ELMOs send XMLs to only one mail adress

.github/workflows/jest.yml
This pull request makes a minor update to the GitHub Actions workflow permissions. The change grants write access to repository contents, which may be required for certain workflow steps.
=> fix: allow coverage badge push in jest workflow

.dockerignore
All 3 ELMO instances are down after merging of my branch.
The most likely reason for that is the following: 
I told container to ignore the /xml folder, and docker-entrypoint.sh changes the ownership of it: 
chown -R www-data:www-data /var/www/html/xml
[Welche Änderungen hast du hierfür vorgenommen?]
[Beschreibung der notwendigen Testschritte]
Changing config files in feature branch is a very bad manner, Sasha....
=> Hotfix: reset the .dockerignore 

composer.lock, package-lock.json
Dependencies update for September to stay secure.
- Bump phpunit/php-code-coverage from 11.0.10 to 11.0.11 and phpunit/phpunit from 11.5.34 to 11.5.39 in composer.lock to include latest fixes and improvements.
- Upgraded various dependencies to their latest versions, including [@babel](https://github.com/babel), [@jest](https://github.com/jest), [@emnapi](https://github.com/emnapi), @types/node, @yaireo/tagify, bootstrap, browserslist, caniuse-lite, debug, dedent, electron-to-chromium, error-ex, expect, and others.
None.
None.
=> Chore: Dependencies update for September

.gitignore, README.md, api/v2/controllers/DraftController.php, api/v2/docs/swagger.yaml, api/v2/index.php, api/v2/routes/api.php, css/gfz-cd.css, doc/changelog.html, footer.html, js/eventhandlers/formgroups/author.js, js/eventhandlers/formgroups/fundingreference.js, js/eventhandlers/formgroups/relatedwork.js, js/eventhandlers/formgroups/stc.js, js/eventhandlers/functions.js, js/language.js, js/saveHandler.js, js/services/autosaveService.js, js/submitHandler.js, js/validation.js, lang/de.json, lang/en.json, lang/fr.json, modals.html, tests/DraftControllerTest.php, tests/js/autosaveRepeaters.test.js, tests/js/autosaveService.test.js, tests/js/saveHandler.test.js, tests/playwright/autosave.spec.ts, tests/playwright/features/autosave.spec.ts
This pull request introduces autosave functionality for dataset drafts, enhancing the user experience by automatically saving form progress and allowing users to restore drafts from previous sessions. The implementation includes backend API endpoints, frontend integration with autosave status indicators, and comprehensive tests for the new draft management features.
* Added a new `DraftController` with REST API endpoints for creating, updating, deleting, and retrieving draft dataset forms, as well as fetching the latest draft for the current session. (`api/v2/controllers/DraftController.php`, `api/v2/routes/api.php`, `api/v2/index.php`) [[1]](diffhunk://#diff-df40779a952ef6bed2a68ca3827ca48b8bdf44ff2e94754b4f04162da7693282R13) [[2]](diffhunk://#diff-5752d19ecc50963640927435b485fa6840e5b202 …
=> Feature: Autosave drafts
