js/select.js

Bugfix: Problem beim Rollen-API-Call behoben

Rollen-API-Aufruf behoben

---

api/v2/controllers/DatasetController.php
api/v2/index.php
save/save_data.php

Fixed #114: DatasetController umgebaut auf Case Senitivität, Ordnerpfade für Zwischenspeicherung von XML-Dateien relativiert

Hotfix für Bug in der API

---

.github/workflows/php.yml
install.php
save/formgroups/save_authors.php
save/formgroups/save_fundingreferences.php
save/formgroups/save_relatedwork.php
tests/SaveAuthorsTest.php
tests/SaveContactpersonsTest.php
tests/SaveContributorsTest.php
tests/SaveDescriptionsTest.php
tests/SaveFreekeywordsTest.php
tests/SaveFundingreferencesTest.php
tests/SaveOriginatingLaboratoryTest.php
tests/SaveRelatedworkTest.php
tests/SaveResourceInformationAndRightsTest.php
tests/SaveSpatialTemporalCoverageTest.php
tests/SaveThesauruskeywordsTest.php

Implementierung von automatisierten Tests beim Pull:
- PHP.yml angepasst zwecks Test von automatisierten Tests in PHPUnit über Composer.
- Automatisierte Erstellung der Testdatenbank implementiert.
- Reset der Testdatenbank in cleanupTestData() ergänzt.
- Fehlerhafte Tests gefixt.

Automatisierte Tests

---

footer.html
formgroups/contributors.html
js/buttons.js
js/roles.js
js/select.js

In diesem Brunch wurden die Roles-Felder von Chosen auf Tagify umgestellt und die Chosen-Einbindung von der "footer" Datei entfernt.

Pull Request zum Brunch "Future/tagify roles felder"

---

README.md
footer.html
formgroups/contributors.html
formgroups/fundingreference.html
formgroups/relatedwork.html
header.html
js/buttons.js

**Verbesserung der Barrierefreiheit und der Entfernung von Warnungen in der Browser durch folgende Maßnahmen:**
- Fixed #178 
- Fixed #207 
- [Tagify Update auf 4.32.1](https://github.com/yairEO/tagify/releases/tag/v4.32.1).
- `ReadMe` aktualisiert.
- Abschnitt `Dependencies` in `ReadMe` übersetzt.
- Kommentare in bearbeiteten HTML-Dateien auf Englisch übersetzt.

Fix für HTML-Attribute

---

save/formgroups/save_contributors.php

Liebe @jaFHP in diesem Brunch wurde den Fehler bei der Speicherung der Rollen von "Contributors" in der Datenbank behoben (fixed #229) 
Es wurde eine JSON-Dekodierung für die Rollen-Eingabe hinzugefügt

Bugfix: Speicherung der Rollen von Contributors

---

README.md
doc/changelog.html
footer.html
header.html

Dieser Pull Request aktualisiert die **Tagify-Bibliotheksversion**.
* Updated Tagify library from version 4.32.2 to 4.33.0 in `README.md`, `footer.html`, and `header.html`. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L41-R41) [[2]](diffhunk://#diff-86e633fe0493da5e3a927455882c9457e09813c83b66900a19765ee3c8b0ed22L75-R77) [[3]](diffhunk://#diff-a850690902505a7657bcedff55c4ec82835dc58e18a3e5a2ed56f7cc127edb50L20-R21)
* Added a new version entry for 2.0.0RC1 in `doc/changelog.html`, including new features and bug fixes.
* Adjusted the version numbers and headers for previous versions in `doc/changelog.html`. [[1]](diffhunk://#diff-7f42e3dbab923ae06d6408cdca2b7166f6e9225a228fcbd07b2d8a18074464cbL49-R88) …

Fix: Tagify Update auf Version 4.33.0

---

header.html

hotfix impressum

---

README.md
doc/changelog.html
doc/help.html
formgroups/mslKeywords.html
formgroups/thesaurusKeywords.html
js/freekeywordTags.js
js/mappingXmlToInputFields.js
js/thesauri.js

in diesem Branch wird das Laden aller Keywordfelder umgesetzt:
fixed
- #329 
- #328 
- #326 
Außerdem wurden die Hilfetexte und die Readme für alle drei formgroups überarbeitet und übersetzt.  für die Keyword-Formgroups habe ich keinen Formgroup Hilfetext geschrieben, da es ja nur ein Feld mit Hilfebutton gibt. Fixed:
- #312 
- #311 
- #310 
- #348 
- #344 
- #346 
Funktion Process Keywords zu mappingXmlToInputField,js hinzugefügt. Namen für Tagify initialisierungen disambiguiert und den jeweiligen Eingabefeldern zugeordnet.
Readme übersetzt und angepasst.
Hilfe angepasst.
Load für alle 3 Keyword-Felder testen
Readme und Hilfetexte auf Verständlichkeit und Vollständigkeit überprüfen
mir fallen keine ein

Load Keywords

---

api/v2/controllers/DatasetController.php
schemas/Freestyle/FreestyleSchemaDB.xsd
schemas/Mappings/FreestyleToDatacite.mfd
schemas/XSLT/MappingMapToDataCiteSchema45.xslt
tests/SeleniumTests/Tests_MDE.side
xml/dataset2.xml
xml/dataset3.xml

- Grant Number wird wieder gemappt -> #384 
- Ror ID bei Publisher entfernt (da falsch) () -> #400 
- DateCollected wird richtig und mit Timezone gemappt -> #392 
- Free Keywords EPOS und multi-scale Laboratories nicht mehr hinzugefügt -> #405 
- nameIdentifier für Author und Contributor Person nur anlegen, wenn ORCID angegeben ist (hatte ich vergessen als Issue aufzuschreiben)
- Freestyle Schema angepasst, damit leeres `</fundingReferences>` Element wird nicht mehr generiert wird (auch hier gabs leider kein Issue)
updated FreestyleToDatacite.mfd and MappingMapToDataCiteSchema45.xslt
- Selenium Tests angepasst
- Testdatensätze neu erzeugt
Freue mich, wenn ihr ausführlich testet, ich werd wenn möglich am Wochenende reingucken und Änderungen sonst spätestens am Montag umsetzen.
passt hier …

update Mapping 2 DataCite

---

README.md
api.php
api/v2/controllers/VocabController.php
api/v2/docs/swagger.yaml
api/v2/routes/api.php
doc/changelog.html

Dieser Pull Request überführt einen veralteten APIv1-Enpunkt getRorAffiliations in den neuen **APIv2-Endpunkt /update/ror**.
This pull request introduces several changes related to updating and managing ROR (Research Organization Registry) affiliations in the project. The most important changes include the addition of a new API endpoint for updating ROR affiliations, deprecation notices for older methods, and updates to documentation and versioning.
* [`api/v2/controllers/VocabController.php`](diffhunk://#diff-b9667eda042481bdf5e70cbb02cd5b4e00a9ccc21b5ea5de5e8437c68bff2fa8R886-R1015): Added a new method `getRorAffiliations` to update ROR affiliations by downloading and processing the latest ROR data dump. This method handles fetching metadata, downloading, extracting, processing, and …

Feature: New APIv2 endpoint /update/ror

---

README.md
doc/changelog.html
doc/help.html
formgroups/resourceInformation.html
install.php
js/buttons.js
js/mappingXmlToInputFields.js
schemas/DataCite/DataCiteExample45.xml
tests/SaveResourceInformationAndRightsTest.php
tests/SeleniumTests/Tests_MDE.side
xml/resource_4.xml

fixed:
- #335 
- ich habe das Mapping jeweils als Unterpunkt der Felder aufgenommen, weil hier, anders als in den meisten anderen Formgroups auf sehr verschiedene Element gemappt wird.
- #319 
- Bei den Resource Types habe ich mich dafür entschieden auf die DataCite doku zu verlinken, da sich die kontrollierte Liste mind. von Version 4.3 auf 4.5 verändert hat und man dann nicht bei jeder schema-Änderung die Hilfe neu schreiben muss, sondern nur nen neuen Link einfügen.
- #422  und Hilfe Buttons in geklonte Titelzeilen hinzugefügt (halte ich für sinnvoll)
update readme.me + help.html
included Helpbutton for fg-resourceInformation
bitte auf verständlichkeit usw prüfen. @McNamara84 nur wenn er Lust hat!
Ich habe noch ein Verständnisproblem, zu dem ich K. befragen werde. oder kann mich sonst …

Update Readme + Help Guide for fg Resource Information

---

README.md

Der Abschnitt Installation ist jetzt untergliedert in: "Requirements" (neu), "Quick installation guide" (übernommen aus der vorherigen Installationsanleitung) und "Detailed example installation on Windows 10", eine detaillierte Anleitung für "Laien" am Bsp. von Windows 10 als OS. Die ist per default eingeklappt, sodass man die Infos nur bei Bedarf bekommt. 
- Neugliederung von Installation
- Hinzufügen von Requirements und Detailed example installation on Windows 10
Bitte prüfen, ob die Infos zur Installation alle stimmen, bzw. auch, ob was fehlt. :)
[Welche Probleme mit niedrigerer Priorität bestehen noch?]

Installation README.md Update

---

README.md
doc/changelog.html
doc/help.html
formgroups/descriptions.html
formgroups/originatingLaboratory.html
install.php
js/buttons.js

- #342 
- #339 
- #313 
- #315 
- update Readme.md, help.html 
- Hilfebuttons für die beiden Formgroups eingefügt
- "verloren gegangene" Hilfe für Licenses&Rights wiederhergestellt
- in install.php habe ich die mögliche Zeichenlänge der Descriptions auf 5000 Zeichen hochgesetzt (ist evtl immer noch zu wenig?) und den Textareas eine maxLength von ebenfall 5000 Zeichen gegeben um Datenverlust beim Speichern zu verhindern.
Frage: Ich finde weder beim GFZ Data Services, noch bei DataCite ne Zeichenbegrenzung für z.B. Abstracts. ich habe die hier auf 5000 Zeichen hochgesetzt, was evtl. immer noch zu kurz ist. Sollte darauf in der Hilfe hingewiesen werden?
Ansonsten freue ich mich über Text review. Habe mich in der Hilfe von der [Datacite …

Update Readme&Help Guide for fgs Originating Laboratories + Descriptions

---

README.md
doc/changelog.html
footer.html
js/saveHandler.js
js/submitHandler.js
js/validation.js
lang/de.json
lang/en.json
lang/fr.json
modals.html
send_xml_file.php

Dieser Pull Request implementiert die Möglichkeit für Forschende zusätzlich zu den Metadaten ihrer Forschungsdaten auch die **Dringlichkeit, den Link zu den Daten und die Datenbeschreibung** an die Datenkurator:innen übermitteln können.
* [`js/saveHandler.js`](diffhunk://#diff-09eb1ba8869156e52146b45ee3285e3b81225ed8f680df0f44c9af03e4b137eaR1-R133): Introduced a new `SaveHandler` class to manage the saving functionality for dataset metadata, including filename generation and file download.
* [`js/submitHandler.js`](diffhunk://#diff-8f21631a98813c3dbda9cd2abbde76214f739fb4f6751c1769497367ab678703R1-R139): Added a new `SubmitHandler` class to handle the submission of dataset metadata, including privacy checks and AJAX form submission.
* …

Feature: Optimized workflow for submitting dataset

---

css/help.css
doc/help.html

Hier wurden die Abschnitte der Formgroups im Help Guide etwas deutlicher dargestellt.
-  Formatierung der Überschriften u. Absätze
- Hinzufügen der Überschriftenformatierung in help.css
Gerne einmal auf Konsistenz prüfen. Wenn ihr noch andere Ideen/Vorschläge habt, sagt gern Bescheid. :)
[Welche Probleme mit niedrigerer Priorität bestehen noch?]

Guide ueberschriften neuformatieren

---

doc/changelog.html
js/submitHandler.js

Dieser Pull Request behebt das Problem, dass unsere Nutzer:innen irritiert waren, weil das **Drücken der Enter-Taste im Save Modal nicht die Speicherung** auslöste.
* Added a new entry to the changelog indicating that the return command now triggers submission in the submit dialog.
* Added event listeners to focus on the input field when the submit modal is shown and to handle the return key to trigger submission while preventing unintended form submissions.
- Nicht lachen über den Changelog! Das darf ruhig ein eigener Punkt bleiben. ;-)
_Keine._

Fix: Trigger submitting with enter command in submit modal

---

README.md
api/v2/controllers/VocabController.php
doc/changelog.html
formgroups/originatingLaboratory.html
js/buttons.js
js/mappingXmlToInputFields.js
json/msl-labs.json
sample_settings.php
save/formgroups/save_originatinglaboratory.php
tests/SaveOriginatingLaboratoryTest.php

Dieser Pull Request ermöglicht die **Speicherung von ROR-IDs der Affiliations von Originating Labs**.
This pull request includes several changes to improve the handling of laboratory affiliations by incorporating ROR IDs and updating related functionalities. The most important changes include updates to the README documentation, modifications to the API and backend processing, and adjustments to the frontend code.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L419-R419): Updated the controlled list URL and added information about saving `laboratoryRorId` in the backend. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L419-R419) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf874 …

Feature: Saving Originating Labs affiliations with ROR-ID

---

doc/changelog.html
lang/de.json
lang/en.json
lang/fr.json
vendor/composer/InstalledVersions.php
vendor/composer/installed.php

Dieser Pull Request erhöht die **Versionsnummer von ELMO auf 2.0.0**.
* [`doc/changelog.html`](diffhunk://#diff-7f42e3dbab923ae06d6408cdca2b7166f6e9225a228fcbd07b2d8a18074464cbL3-R9): Updated version from 2.0.0RC3 to 2.0.0 in the changelog.
* [`lang/de.json`](diffhunk://#diff-b856eeca8165aed4012d1d98ca6e927f20366c9c1272932ad9d8004358c1f38dL13-R13): Changed `logoTitle` from "ELMO - Enhanced Laboratory Metadata Organizer 2.0RC2" to "ELMO - Enhanced Laboratory Metadata Organizer 2.0".
* [`lang/en.json`](diffhunk://#diff-1d56632a2d162f99c901e53b79a6224e984c14501bca3188a85dbb4b4c5e6da1L13-R13): Changed `logoTitle` from "ELMO - Enhanced Laboratory Metadata Organizer 2.0RC2" to "ELMO - Enhanced Laboratory Metadata Organizer 2.0".
* [`lang/fr.json`](diffhunk://#diff-0ebbae606a5ccb4e55da4ab4b367dd7 …

Versionsnummer auf v2.0.0 erhöht

---

.dockerignore
.env
.env_sample
Dockerfile
README.md
docker-compose.yml
docker-entrypoint.sh
install.php
sample_settings.php

Mit diesem Pull-Request versuche ich, die verlorenen Daten zu Docker wiederzubekommen.

fix: Änderungen an ELMO wiederhergestellt

---

docker-compose.yml
install.php
js/install.js
sample_settings.php
save/save_data.php
send_xml_file.php

This pull request includes updates to improve error handling and relative path usage in the installation process. The changes primarily focus on enhancing user feedback and ensuring compatibility when running the application from subdirectories.
* [`install.php`](diffhunk://#diff-19e3c84c1b3ce87245588ae6ee7791fe3b94c98a8f955ea3e89f9f5865144ca0L13-R22): Added a detailed error message when `settings.php` is missing, instructing users to copy `sample_settings.php` and update their database credentials.
* [`js/install.js`](diffhunk://#diff-67d657dd3a1103d0c7d518c7af28f72c6006ff93a1648f5734811be7303f2689L23-R24): Updated the fetch paths for `install.php` and `generate_xml_files.php` to use relative paths, ensuring the application works correctly when accessed from subdirectories. …

Hotfix: Install script is not working

---

doc/changelog.html

[Beschreibe kurz die vorgenommenen Änderungen und zu welchen Issues diese gehören]
[Welche Änderungen hast du hierfür vorgenommen?]
[Beschreibung der notwendigen Testschritte]
[Welche Probleme mit niedrigerer Priorität bestehen noch?]

Doc: Version bump to 2.0.2 with changelog

---

.github/workflows/php84.yml
README.md
phpunit.xml

This pull request introduces significant updates to the PHP 8.4 test workflow, improves the code coverage reporting, and enhances the project's documentation. The most important changes include debugging and validating the test setup, generating a code coverage badge, updating the `phpunit.xml` configuration for coverage, and adding badges to the `README.md` file.
* [`.github/workflows/php84.yml`](diffhunk://#diff-8ff816be0da5f989d5d284c3327cc9c8acfdd114a977929757ce1793bd15a574L138-R248): Added debugging steps for PHP and Xdebug setup, including checks for installed extensions and configurations. Enhanced PHPUnit test steps with coverage reporting and validation checks. Introduced fallback mechanisms for badge creation when coverage data is missing.
* …

Documentation: Badges in ReadMe

---

.github/workflows/jest.yml
README.md
jest.config.js
package-lock.json
package.json
tests/js/affiliations.test.js

This pull request introduces several changes to enhance testing capabilities, streamline workflows, and improve documentation. The most significant updates include the addition of **Jest testing** workflows, new JavaScript **unit tests for `affiliations.js`**, and modifications to testing instructions in the `README.md`.
Fixes #298 
* **Addition of Jest Testing Workflow**: Introduced a GitHub Actions workflow (`.github/workflows/jest.yml`) to run Jest tests automatically on pushes and pull requests to the `main` branch. This ensures consistent testing across environments.
* **JavaScript Unit Tests for `affiliations.js`**: Added comprehensive Jest-based unit tests (`tests/js/affiliations.test.js`) to validate functionality such as Tagify instance creation, dropdown behavior, tag removal, …

Testing: Unit testing for JavaScript functions

---

README.md
doc/changelog.html
header.php
index.php

This pull request introduces several changes to improve the functionality and maintainability of the project. Key updates include renaming `header.html` to `header.php` to enable dynamic language detection, refactoring language dropdown generation to use PHP, and updating references to the renamed file across the codebase.
Fixes #393 
* Renamed `header.html` to `header.php` and added PHP code to dynamically detect available language files for the dropdown menu. This improves flexibility and scalability for multilingual support. [[1]](diffhunk://#diff-e7f789e333fc7ce27ae3d6999cca0b78637e8b96c734dea9aedb855b278b7eb9R1-R6) [[2]](diffhunk://#diff-e7f789e333fc7ce27ae3d6999cca0b78637e8b96c734dea9aedb855b278b7eb9L98-R108)
* Refactored the language dropdown menu in `header.php` to dynamically …

Feature: Dynamically generate language dropdown

---

doc/changelog.html
formgroups/authors.html
formgroups/contributorPersons.html
js/eventhandlers/formgroups/contributor-organisation.js
js/eventhandlers/formgroups/contributor-person.js
js/saveHandler.js
js/submitHandler.js
lang/de.json
lang/en.json
lang/fr.json
tests/js/saveHandler.test.js
tests/js/submitHandler.test.js

This pull request introduces improvements in user feedback messaging, consistency in translations, and additional test coverage for the `SaveHandler` JavaScript module. The most important changes include the integration of translation keys for dynamic messages, updates to error feedback consistency across forms, and the addition of unit tests to validate key functionalities.
- Closes #420 
- Closes #653 
* Updated `SaveHandler` and `SubmitHandler` classes to use translation keys for dynamic messages, improving localization and consistency. (`js/saveHandler.js`: [[1]](diffhunk://#diff-09eb1ba8869156e52146b45ee3285e3b81225ed8f680df0f44c9af03e4b137eaL180-R188) [[2]](diffhunk://#diff-09eb1ba8869156e52146b45ee3285e3b81225ed8f680df0f44c9af03e4b137eaL205-R211) …

Fix: Translation of messages in save and submit workflow

---

doc/changelog.html

A new changelog for the new milestone was created during this brunch.
No current problems known

Doc: Changelog for Milestone v2.0.4 added

---

formgroups/GGMsTechnical.html
formgroups/dataSources.html
js/eventhandlers/formgroups/ggmproperties-technical.js

Removed unnecessary required tags and corrected Javascript to add or remove it.
-- email functionality is not in the scope of this PR
[Welche Probleme mit niedrigerer Priorität bestehen noch?]

Fix: corrected the required input fields ELMOGEM can save and submit data

---

js/affiliations.js
js/eventhandlers/formgroups/ggmproperties-technical.js
js/select.js
js/thesauri.js

Small fixes that eliminate unnecessary warnings. Fixes #687 
The problem was that not all parts of the code were adapted to recent changes.
Things to test: 
Some map functionality gets deprecated, this issues yellow warning for now and does not affect the functionality

Fix: related work id patterns

---

.github/PULL_REQUEST_REVIEW_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This pull request updates the pull request templates in the `.github` directory to use English instead of German, and improves the clarity and consistency of the review and submission checklists. The changes make the templates more accessible to non-German speakers and standardize the review process.
* [`.github/PULL_REQUEST_TEMPLATE.md`](diffhunk://#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35L1-R29): Translated all sections and checklist items from German to English, clarified instructions for describing changes, test steps, and known issues, and improved the structure and consistency of the checklist.
* [`.github/PULL_REQUEST_REVIEW_TEMPLATE.md`](diffhunk://#diff-7f6209b97b64903d994e25f97537c3712ccbe47b432381d593c782d3abf2aeb6L1-R31): Translated all review …

Chore: Update dev templates

---

doc/changelog.html
formgroups/authors.html
js/eventhandlers/formgroups/author.js
tests/js/authors.test.js

This pull request addresses issues with duplicate IDs and classes in the author form group, improving accessibility and ensuring correct behavior when adding new author rows. The changes also update related tests to verify the uniqueness of IDs and the correct association between labels and inputs.
- Fixes #703 
- Fixes #704 
* Ensured all input fields and their labels in the author form group (`formgroups/authors.html` and `js/eventhandlers/formgroups/author.js`) receive unique IDs when new rows are added, and that labels' `for` attributes are updated accordingly. This prevents duplicate IDs and improves accessibility. [[1]](diffhunk://#diff-0663664b4587a59551a84707268521b397bc126a239cab2f0f955bc1f935561bL78-R78) [[2]](diffhunk://#diff-1242ff2d78606b57599dad907494f391bff32440737e8fdfb9022 …

Fix: Duplicate classes and IDs
